### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by skwerlman** [Belethors-General-Mods/belethor#32]
We have 17 branches on this repo, and not all are needed. Below is a list of them with markers to designate whether we should keep them. This issue will be updated as each branch is reviewed for usefulness.

Icon | Meaning
-|-
✅|Keep this around
❎|Delete this branch
⭕|Get this merged
❔|Unknown/unevaluated

- [x] ✅ master
- [ ] ⭕ design
- [x] ❎ feature/add-common
- [x] ❎ feature/brunch-vul-fix
- [x] ❎ feature/coc
- [x] ❎ feature/compile-time-error
- [x] ❎ feature/crawler_arch
- [ ] ⭕ feature/credo-changes
- [x] ❎ feature/default.nix
- [x] ❎ feature/fix-missing-docs
- [x] ❎ feature/misc-changes
- [x] ❎ feature/misc-cleanup
- [x] ❎ feature/misc-redo
- [x] ❎ feature/phx-upgrade
- [ ] ⭕ feature/private.nix
- [x] ❎ feature/test-config
- [x] ❎ feature/update-deps

**Comment by skwerlman** [comment]
with the majority removed (only unmerged branches remain), im closing this
